name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '10 12,17,23 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  test: testcontentAAAAAAAAAAAAAAAAAA
#   apk-name: maimemo.apk
#   apk-url: https://cdn.maimemo.com/apk/maimemo_v3.8.56_1617086292.apk

jobs:
  
  setup-python:
    runs-on: macos-latest
    env: 
      python-version: 3.8
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - run: pip install -r requirements.txt 
  
  ensure-apk:
    runs-on: macos-latest
    env:
      apk-name: maimemo.apk
      apk-url: https://cdn.maimemo.com/apk/maimemo_v3.8.56_1617086292.apk
    steps:
      - uses: actions/checkout@v2
      - name: Cache apk
        uses: actions/cache@v2
        id: apk-cache
        with:
          path: ./${{ env.apk-name }}
          key: ${{ env.apk-url }}
      - name: download apk
        if: steps.apk-cache.outputs.cache-hit != 'true'
        run: |
          wget -q -O ${{ env.apk-name }} ${{env.apk-url}}
      - name: check exists    
        run: |
          echo ${{ env.test }}
          [ -f ${{ env.apk-name }} ]
  
  setup-emulator:
    # The type of runner that the job will run on
    runs-on: macos-latest
    needs: [setup-python,ensure-apk]
    env:
      api-level: 29

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: /bin/sh install_momo.sh

          
