name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '10 12,17,23 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  setup-python:
    runs-on: macos-latest
    env: 
      python-version: 3.8
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - run: pip install -r requirements.txt 
  
  
  setup-env:
    # The type of runner that the job will run on
    runs-on: macos-latest
    needs: [setup-python]
    env:
      api-level: 29

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo ${{ env.python-version }};exit 1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: /bin/sh install_momo.sh

          
